# ==========================================================
# JOB SERVICE
# ==========================================================

# Database
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/job_db

spring.datasource.username=${JOB_DB_USERNAME:root}

spring.datasource.password=${JOB_DB_PASSWORD:root}


# ==========================================================
# JPA
# ==========================================================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.database=mysql


# ==========================================================
# Kafka Producer
# ==========================================================

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.producer.properties.spring.json.add.type.headers=false

spring.kafka.topic.name=notificationTopic


# ==========================================================
# Kafka JSON
# ==========================================================

spring.kafka.consumer.properties.spring.json.value.default.type=com.example.springboot.job_service.request.SendNotificationRequest
